author: Michel Lutz
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLStackController
root_url: https://micheltlutz.github.io/MLStackController/
module: MLStackController
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLStackController.xcworkspace', -scheme, 'MLStackController-iOS']
